<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net8.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <NeutralLanguage>ru-RU</NeutralLanguage>
    <AssemblyVersion>2.1.0</AssemblyVersion>
    <Copyright>Copyright © 2025</Copyright>
    <Description>Библиотека для упрощённого преобразования данных из БД в объекты классов</Description>
    <Company>BlueYellow</Company>
    <Version>$(AssemblyVersion)</Version>
    <Title>$(AssemblyName)</Title>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Nullable>enable</Nullable>    
  </PropertyGroup>
  
</Project>
